version: '3.4'

services:
  dockersample01:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "7002"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro